on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo issue : ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          echo PR : ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
          echo Result : ${{ contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.pull_request.labels.*.name, 'bug') }}
