on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  issue_comment:
    types:
      - created

jobs:
  test:
    if: ${{ github.event.issue.labels || github.event.pull_request.labels }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo issue : ${{ fromJSON(github.event.issue.labels) }}
          echo PR : ${{ fromJSON(github.event.pull_request.labels) }}
          echo For the test
